import React from 'react';
import { useEffect, useState } from 'react';
import { currentUser } from '../api/client';
import { organizations, roles, users as fallbackUsers } from '../data/organizations';
export default function AdministrationPage({ section='organizations' }){
 const [user,setUser]=useState(null); useEffect(()=>{currentUser().then(r=>setUser(r.user)).catch(()=>{});},[]);
 const isAccess=section==='access'; const orgs=user?.organizations?.length?user.organizations:organizations; const users=fallbackUsers;
 return <section className="content"><div className="hero"><div><span className="eyebrow">ADMINISTRATION</span><h2>{isAccess?'Utilisateurs, rôles & permissions':'Organisations'}</h2><p>{isAccess?'Maîtrisez les responsabilités et les droits de chaque profil.':'Gérez les espaces financiers, exercices et devises de votre portefeuille.'}</p></div><button className="primary">+ {isAccess?'Inviter un utilisateur':'Nouvelle organisation'}</button></div>
 <div className="stats-grid">{isAccess?<><article className="stat-card"><span>Utilisateurs</span><strong>{users.length}</strong><small>comptes</small></article><article className="stat-card"><span>Rôles</span><strong>{roles.length}</strong><small>profils</small></article><article className="stat-card"><span>Actifs</span><strong>{users.filter(u=>u.status==='active').length}</strong><small>accès actifs</small></article><article className="stat-card"><span>Permissions</span><strong>8</strong><small>droits fonctionnels</small></article></>:<><article className="stat-card"><span>Organisations</span><strong>{orgs.length}</strong><small>espaces financiers</small></article><article className="stat-card"><span>Devise</span><strong>XOF</strong><small>référentiel principal</small></article><article className="stat-card"><span>Exercice</span><strong>2026</strong><small>période active</small></article><article className="stat-card"><span>Sécurité</span><strong>Sanctum</strong><small>API authentifiée</small></article></>}</div>
 <div className="grid-two"><section className="panel"><div className="panel-head"><div><span className="eyebrow">RÉFÉRENTIEL</span><h3>{isAccess?'Comptes utilisateurs':'Espaces organisationnels'}</h3></div></div><div className="operation-list">{(isAccess?users:orgs).map(item=><div key={item.id}><span className="operation-icon">{isAccess?item.name?.charAt(0):'O'}</span><div><strong>{item.name}</strong><small>{isAccess?`${item.email} · ${item.role}`:`${item.code || 'ORG'} · ${item.country || 'Bénin'} · ${item.currency || 'XOF'}`}</small></div><b>{isAccess?(item.status==='active'?'Actif':'En attente'):'Actif'}</b></div>)}</div></section>
 <section className="panel"><div className="panel-head"><div><span className="eyebrow">GOUVERNANCE</span><h3>{isAccess?'Rôles disponibles':'Paramètres de contrôle'}</h3></div></div><div className="operation-list">{isAccess?roles.map(r=><div key={r.id}><span className="operation-icon revenue-icon">R</span><div><strong>{r.name}</strong><small>{r.description}</small></div><b>{r.permissions} droits</b></div>):['Isolation par organisation','Exercice fiscal configurable','Devise XOF','Traçabilité des opérations'].map(item=><div key={item}><span className="operation-icon revenue-icon">✓</span><div><strong>{item}</strong><small>Paramètre actif dans l’espace Finance Pro.</small></div></div>)}</div></section></div></section>;
}
