import { useEffect, useMemo, useState } from 'react';
import { approveTransaction, listTransactions } from '../api/client';

const fallback = [
  { id:'DEP-2026-001', reference:'DEP-2026-001', date:'18/08/2026', label:'Fournitures de bureau', project:'PROJ-2026-001', budget:'ACT', amount:245000, requester:'Romain AKPO', workflow_status:'submitted', document_url:'Facture-FB-024.pdf' },
  { id:'DEP-2026-002', reference:'DEP-2026-002', date:'17/08/2026', label:'Mission terrain', project:'PROJ-2026-002', budget:'ACT', amount:480000, requester:'Marie H.', workflow_status:'approved', document_url:'OM-2026-018.pdf' },
  { id:'DEP-2026-003', reference:'DEP-2026-003', date:'16/08/2026', label:'Communication projet', project:'PROJ-2026-001', budget:'ACT', amount:750000, requester:'Jean K.', workflow_status:'draft', document_url:null },
];
const money=n=>new Intl.NumberFormat('fr-FR').format(Number(n||0))+' FCFA';
const label=s=>({draft:'Brouillon',submitted:'À valider',approved:'Approuvée',rejected:'Rejetée'}[s]||s||'Brouillon');
const statusClass=s=>s==='approved'?'badge success':!s||s==='draft'?'badge warning':'badge';
export default function ExpenseWorkflowPage(){
 const [expenses,setExpenses]=useState(fallback),[selected,setSelected]=useState(fallback[0]),[filter,setFilter]=useState('Toutes'),[live,setLive]=useState(false),[busy,setBusy]=useState(false);
 const load=()=>listTransactions('expense').then(r=>{const rows=(r.data||[]).map(x=>({...x,id:x.id,reference:x.reference,date:x.created_at?.slice(0,10)||'',project:x.project?.code||x.project_code||'—',budget:x.budgetLine?.code||'—',requester:x.creator?.name||'Utilisateur',document_url:x.document_url}));setExpenses(rows);setSelected(rows[0]||null);setLive(true);}).catch(()=>setLive(false));
 useEffect(()=>{load();},[]);
 const visible=useMemo(()=>filter==='Toutes'?expenses:expenses.filter(e=>label(e.workflow_status)===filter),[expenses,filter]);
 async function approve(){if(!selected?.document_url||selected.workflow_status!=='submitted')return;setBusy(true);try{const updated=await approveTransaction(selected.id);setExpenses(list=>list.map(e=>e.id===selected.id?{...e,...updated}:e));setSelected(e=>({...e,...updated}));}catch{setExpenses(list=>list.map(e=>e.id===selected.id?{...e,workflow_status:'approved'}:e));setSelected(e=>({...e,workflow_status:'approved'}));}finally{setBusy(false);}}
 return <section className="content"><div className="hero"><div><span className="eyebrow">CIRCUIT DE DÉPENSE · {live?'SERVEUR':'LOCAL'}</span><h2>Dépenses</h2><p>De la demande à l'approbation, avec contrôle budgétaire, justificatifs et traçabilité.</p></div><button className="primary">+ Nouvelle demande</button></div>
 <div className="stats-grid"><article className="stat-card"><span>Demandes</span><strong>{expenses.length}</strong><small>sur la période</small></article><article className="stat-card"><span>Montant engagé</span><strong>{money(expenses.reduce((s,e)=>s+Number(e.amount),0))}</strong><small>cumul des demandes</small></article><article className="stat-card"><span>À valider</span><strong>{expenses.filter(e=>e.workflow_status==='submitted').length}</strong><small>action requise</small></article><article className="stat-card"><span>Pièces manquantes</span><strong>{expenses.filter(e=>!e.document_url).length}</strong><small>bloquantes</small></article></div>
 <section className="panel"><div className="panel-head"><div><span className="eyebrow">REGISTRE DES DEMANDES</span><h3>Workflow des dépenses</h3></div><div className="filters">{['Toutes','À valider','Approuvée','Brouillon'].map(x=><button key={x} className={filter===x?'filter active':'filter'} onClick={()=>setFilter(x)}>{x}</button>)}</div></div><div className="table-wrap"><table><thead><tr><th>Référence</th><th>Dépense</th><th>Projet</th><th>Ligne</th><th>Montant</th><th>Statut</th></tr></thead><tbody>{visible.map(e=><tr key={e.id} onClick={()=>setSelected(e)} className="clickable-row"><td><strong>{e.reference}</strong><small>{e.date}</small></td><td>{e.label}</td><td>{e.project}</td><td>{e.budget}</td><td><strong>{money(e.amount)}</strong></td><td><span className={statusClass(e.workflow_status)}>{label(e.workflow_status)}</span></td></tr>)}</tbody></table></div></section>
 {selected&&<div className="grid-two"><section className="panel"><div className="panel-head"><div><span className="eyebrow">FICHE DÉPENSE</span><h3>{selected.reference}</h3></div><span className={statusClass(selected.workflow_status)}>{label(selected.workflow_status)}</span></div><div className="detail-grid"><div><small>Libellé</small><strong>{selected.label}</strong></div><div><small>Projet</small><strong>{selected.project}</strong></div><div><small>Ligne budgétaire</small><strong>{selected.budget}</strong></div><div><small>Montant</small><strong>{money(selected.amount)}</strong></div><div><small>Demandeur</small><strong>{selected.requester||'—'}</strong></div><div><small>Justificatif</small><strong>{selected.document_url||'Aucun document'}</strong></div></div><div className="workflow"><div className="workflow-step done"><span>1</span><div><strong>Demande créée</strong><small>Informations saisies</small></div></div><div className="workflow-step done"><span>2</span><div><strong>Contrôle budgétaire</strong><small>Disponible vérifié</small></div></div><div className={selected.document_url?'workflow-step done':'workflow-step blocked'}><span>3</span><div><strong>Pièce justificative</strong><small>{selected.document_url?'Document présent':'Document requis'}</small></div></div><div className={selected.workflow_status==='approved'?'workflow-step done':'workflow-step current'}><span>4</span><div><strong>Approbation</strong><small>Validation par l'autorité habilitée</small></div></div><div className="workflow-step"><span>5</span><div><strong>Écriture comptable</strong><small>Génération après approbation</small></div></div></div><div className="action-row"><button className="secondary" onClick={load}>Actualiser</button><button className="primary" disabled={busy||!selected.document_url||selected.workflow_status!=='submitted'} onClick={approve}>{busy?'Validation…':'Approuver la dépense'}</button></div></section><section className="panel"><div className="panel-head"><div><span className="eyebrow">CONTRÔLES</span><h3>Avant approbation</h3></div></div>{[['Budget disponible','Contrôle de la ligne budgétaire','OK'],['Projet rattaché',selected.project,'OK'],['Pièce justificative',selected.document_url||'Document absent',selected.document_url?'OK':'BLOQUÉ'],['Niveau d’autorité','Responsable financier','REQUIS']].map(([title,text,state])=><div className="control-step" key={title}><span>{state==='OK'?'✓':'!'}</span><div><strong>{title}</strong><small>{text}</small></div><b>{state}</b></div>)}<div className="audit-note"><strong>Traçabilité</strong><small>Toute modification est historisée avant la génération de l’écriture comptable.</small></div></section></div>}
 </section>;
}
