import React from 'react';
import { useMemo, useState } from 'react';
import { logout, TOKEN_KEY } from './api/client';
import DashboardPage from './pages/DashboardPage';
import AdministrationPage from './pages/AdministrationPage';
import ProjectsPage from './pages/ProjectsPage';
import ExpenseWorkflowPage from './pages/ExpenseWorkflowPage';
import RevenueWorkflowPage from './pages/RevenueWorkflowPage';
import BudgetControlPage from './pages/BudgetControlPage';
import AccountingPage from './pages/AccountingPage';
import ReportsPage from './pages/ReportsPage';
import SubscriptionPage from './pages/SubscriptionPage';
const navigation=[{id:'dashboard',label:'Tableau de bord',section:'PILOTAGE'},{id:'organizations',label:'Organisations',section:'ADMINISTRATION'},{id:'access',label:'Utilisateurs & rôles',section:'ADMINISTRATION'},{id:'projects',label:'Projets & budgets',section:'FINANCE'},{id:'expenses',label:'Dépenses',section:'FINANCE'},{id:'revenues',label:'Recettes & financements',section:'FINANCE'},{id:'budget-control',label:'Contrôle budgétaire',section:'FINANCE'},{id:'accounting',label:'Comptabilité',section:'COMPTABILITÉ'},{id:'reports',label:'Rapports & analyses',section:'COMPTABILITÉ'},{id:'subscription',label:'Abonnement & facturation',section:'ADMINISTRATION'}];
export default function App(){const[active,setActive]=useState('dashboard');const[online,setOnline]=useState(false);const[mobileOpen,setMobileOpen]=useState(false);const current=navigation.find(x=>x.id===active)||navigation[0];const groups=useMemo(()=>[...new Set(navigation.map(x=>x.section))],[]);async function handleLogout(){try{await logout()}catch(_){}localStorage.removeItem(TOKEN_KEY);window.location.reload()}function renderPage(){switch(active){case'dashboard':return <DashboardPage/>;case'organizations':return <AdministrationPage section="organizations"/>;case'access':return <AdministrationPage section="access"/>;case'projects':return <ProjectsPage/>;case'expenses':return <ExpenseWorkflowPage/>;case'revenues':return <RevenueWorkflowPage/>;case'budget-control':return <BudgetControlPage/>;case'accounting':return <AccountingPage/>;case'reports':return <ReportsPage/>;case'subscription':return <SubscriptionPage/>;default:return <DashboardPage/>}}return <div className="app-shell"><aside className={mobileOpen?'sidebar sidebar-open':'sidebar'}><div className="brand"><div className="brand-mark">F</div><div><strong>Finance Pro</strong><span>Gestion financière ONG</span></div><button className="mobile-close" onClick={()=>setMobileOpen(false)}>×</button></div><div className="workspace"><span>Organisation active</span><strong>Mon ONG</strong><small>Exercice 2026 · XOF</small></div><nav aria-label="Navigation principale">{groups.map(group=><div className="nav-group" key={group}><small className="nav-label">{group}</small>{navigation.filter(x=>x.section===group).map(item=><button key={item.id} className={active===item.id?'nav-item active':'nav-item'} onClick={()=>{setActive(item.id);setMobileOpen(false)}}><span className="nav-icon">{item.label.charAt(0)}</span><span>{item.label}</span></button>)}</div>)}</nav><div className="sidebar-bottom"><div className={online?'sync-card online':'sync-card'}><div><span className="status-dot"/>{online?'Serveur connecté':'Mode local'}</div><small>{online?'Synchronisation disponible':'Les écrans restent consultables localement'}</small><button onClick={()=>setOnline(v=>!v)}>{online?'Passer en mode local':'Simuler la connexion'}</button></div><button className="logout-button" onClick={handleLogout}>Se déconnecter</button></div></aside><main className="main-content"><header className="topbar"><div className="topbar-left"><button className="mobile-menu" onClick={()=>setMobileOpen(true)}>☰</button><div><span className="eyebrow">FINANCE PRO / 2026</span><h1>{current.label}</h1></div></div><div className="top-actions"><span className="connection"><i className={online?'connected':''}/>{online?'En ligne':'Local'}</span><button className="icon-button" aria-label="Notifications">●</button><button className="profile-button">RA</button></div></header>{renderPage()}</main></div>}
